@startuml
title SmartHome Context Diagram

top to bottom direction

!includeurl ../C4_Context.puml

Person_Ext(user, "User", "- добавление устройств\n- мониторинг датчиков\n- управление реле\n- создание сценариев\n- видеонаблюдение")
Person(manager, "Manager", "добавление новых типов устройств")
Person(operator, "Operator", "- поддержка\n- просмотр данных пользователей")

System(SmartHomeSystem, "SmartHome", "реализует все функции умного дома")

System_Ext(sensors, "Sensors", "- внешние 1P датчики\n- внешние 3P датчики")
System_Ext(relays, "Relays", "- внешние 1P реле\n- внешние 3P реле")
System_Ext(cameras, "IP cameras", "видеонаблюдение")
System_Ext(banks, "Bank System", "- процессинг платежей")
System_Ext(ext_notify_systems, "ExtNotifySystems", "-sms\n- telegram\n- e-mail")
SystemDb_Ext(s3, "S3", "Внешнее хранилище данных")

Rel(user, SmartHomeSystem, "Использует\nсистему")
Rel(operator,SmartHomeSystem,"Расширенный\nдоступ")
Rel(manager, SmartHomeSystem, "Менеджмент\nустройств и ролей")
Rel(SmartHomeSystem, banks, "Проведение платежей")

Rel(sensors,SmartHomeSystem,"MQTT\nтелеметрия")
Rel(SmartHomeSystem,sensors,"Force\npolling")

Rel(relays,SmartHomeSystem,"MQTT\ncостояние")
Rel(SmartHomeSystem,relays,"MQTT\nкоманды")

Rel(SmartHomeSystem,s3,"Сохранение и просмотр видео и архивов метрик")
Rel(SmartHomeSystem,ext_notify_systems,"Отправка уведомлений")
Rel(cameras,SmartHomeSystem,"Стриминг видео")

@enduml