FROM eclipse-temurin:17-jdk

WORKDIR /app

# Копируем локально собранный JAR внутрь контейнера
COPY build/libs/temperature-api-*.jar app.jar

EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar", "--server.port=8081", "--logging.level.org.springframework.boot.context=DEBUG"]