@startuml
title WarmHouse C4 Context Diagram

top to bottom direction

!includeurl ../C4_Context.puml

Person_Ext(user, "User", "Мониторинг температуры и управление реле отопления")
Person(admin, "Admin", "Добавляет/удаляет устройства")
System(WarmHouseSystem, "WarmHouse", "Контроль температуры и управление отоплением")

System_Ext(sensors, "Sensors", "Внешние датчики температуры")
System_Ext(relays, "Relays", "Внешние реле отопления")

Rel(user, WarmHouseSystem, "Использует\n систему")
Rel(admin,WarmHouseSystem,"Менеджмент\n устройств")
Rel(WarmHouseSystem,sensors,"Опрашивает датчики температуры")
Rel(WarmHouseSystem,relays,"Включает/отключает реле")

@enduml